version: '3.8'

services:
  # Servizio 1: Pulizia Dati
  processor:
    build: ./data_processor
    container_name: med_processor
    ports:
      - "8001:8001"
    networks:
      - med_network

  # Servizio 2: Intelligenza Artificiale
  ai-brain:
    build: ./ai_service
    container_name: med_brain
    ports:
      - "8000:8000"
    volumes:
      # Monta la tua cartella models dentro il container
      - ./models:/app/models
    env_file:
      - .env
    networks:
      - med_network
    depends_on:
      - processor

networks:
  med_network:
    driver: bridge